// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// So far, I haven't been able to get Stimulus to work in this app.
import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
